site_name: Blitz API Documentation

theme:
  name: material
  favicon: favicon.ico
  logo: icon.png
  features:
    - navigation.expand
    - content.code.copy
    - navigation.sections
    - navigation.tracking
    - toc.follow


  copyright: "this is copyright"

extra_css:
  - css/custom.css

  
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      toc_depth: 2

nav:

  - Introduction: index.md
  - Authentication: Authentication.md
  - Trading APIs:
    - Orders : orders.md
    - Trades : trades.md
    - Positions : positions.md
  

  - Market Data APIs:
    - Last Trading Price: LTP.md
    - Option Chain: optionchain.md
    - Market Quote: marketquote.md
    - Historical Data: historicaldata.md
  